# Generated by Django 5.1.7 on 2025-03-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('hours', models.TimeField(auto_now_add=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('completed', 'Concluído'), ('canceled', 'Cancelado')], default='pending', max_length=10)),
            ],
        ),
    ]
