# Generated by Django 5.1.7 on 2025-03-20 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='date',
        ),
        migrations.RemoveField(
            model_name='service',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='service',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='service',
            name='status',
        ),
    ]
